[pip]
index-url = "https://mirrors.aliyun.com/pypi/simple/"

[[index]]
url = "https://mirrors.aliyun.com/pypi/simple/"
default = true
[[index]]
name = "pytorch-cu129"
url = "https://download.pytorch.org/whl/cu129"

