"""The answer contract: one vocabulary, bound once, shared by both languages.

`fpg` (the installed package, not this module) owns the invariant half of the
fault propagation graph — node shapes, graph rules, evidence structure — and
`configs/fpg/microservices.toml` owns the variable half: which failure modes a node
may assert, which channels an edge may name, which entity kinds a subject may
refer to. Binding the two is `fpg.build_schema`, and this module is the one
place that binds them, so a submission, the ground truth it will be scored
against, and the tool that produced it all answer to the same value space.

The harness tool is JavaScript and cannot import a Python profile, so `main`
projects the vocabulary into `agent/rca-harness/src/vocabulary.js`, which is
generated and committed; `scripts/check.sh` and
`tests/test_submit_result_contract.py` both fail when it drifts from the
profile. Generating rather than restating is the point. The tool's schema was
previously written by hand against this same shape, and it reproduced the field
names while enforcing none of the rules — every one of the 98 nodes the first
ten collected episodes submitted was out of contract.
"""

from __future__ import annotations

import json
import sys
import typing
from collections.abc import Mapping
from functools import cache
from pathlib import Path

from fpg import SchemaBundle, build_schema, load_profile
from fpg.model_output import ModelRCAOutput
from fpg.vocab import QueryLanguage

REPO_ROOT = Path(__file__).resolve().parents[2]
PROFILE_PATH = REPO_ROOT / "configs" / "fpg" / "microservices.toml"
VOCABULARY_JS = REPO_ROOT / "agent" / "rca-harness" / "src" / "vocabulary.js"


@cache
def schema() -> SchemaBundle:
    """The RCABench-bound models. Cached: `build_schema` creates pydantic classes."""
    return build_schema(load_profile(PROFILE_PATH))


def entity_ref_pattern() -> str:
    """The regex the bound models hold entity references to.

    Read off the generated type rather than restated, so the JavaScript tool
    cannot enforce a subject format the Python verifier would reject.
    """
    (metadata,) = typing.get_args(schema().EntityRef)[1].metadata
    pattern: str = metadata.pattern
    return pattern


def parse_submission(arguments: str | Mapping[str, object]) -> ModelRCAOutput:
    """Validate one `submit_result` payload against the bound contract.

    Raises `pydantic.ValidationError` when the submission is out of contract —
    which is a fact about the episode, not an accident: the tool applies the
    same rules before it accepts the call, so a stored submission that fails
    here means the two sides have drifted.
    """
    data = json.loads(arguments) if isinstance(arguments, str) else arguments
    return typing.cast(ModelRCAOutput, schema().ModelRCAOutput.model_validate(data))


def render_vocabulary_js() -> str:
    """The generated JavaScript projection of the profile."""
    bundle = schema()
    profile = bundle.profile
    # From the bound enum, not the profile, so the list carries fpg's
    # factory-injected `other` and the two sides accept exactly the same values.
    briefs = {value: entry.brief for value, entry in profile.node_predicates.items()}
    predicates = [
        {
            "value": member.value,
            "brief": briefs.get(
                member.value,
                "None of the above; say what the failure mode is in the evidence "
                "explanation. A recurring `other` is a missing vocabulary entry.",
            ),
        }
        for member in bundle.NodePredicate
    ]
    entities = [
        {"prefix": prefix, "brief": spec.brief} for prefix, spec in profile.entity_types.items()
    ]
    body = "\n".join(
        [
            "// GENERATED by `python -m autorl.fpg` from configs/fpg/microservices.toml.",
            "// Do not edit: `scripts/check.sh` fails when this drifts from the profile.",
            "// The profile is the vocabulary's single source of truth and `fpg` the",
            "// structure's; this file only carries them across the language boundary",
            "// into the tool that must reject an out-of-contract submission before it",
            "// becomes a training example.",
            "",
            f"export const VOCAB_VERSION = {json.dumps(profile.vocab_version)}",
            "",
            "/** Entity-reference format, byte-identical to the pattern the bound",
            " * pydantic models enforce. */",
            f"export const ENTITY_REF_PATTERN = {json.dumps(entity_ref_pattern())}",
            "",
            "/** Entity kinds a `subject` may name, coarsest first. */",
            f"export const ENTITY_TYPES = {_js(entities)}",
            "",
            "/** Failure modes a node may assert. `other` is the escape hatch fpg",
            " * injects into every generated enum. */",
            f"export const NODE_PREDICATES = {_js(predicates)}",
            "",
            "/** Evidence query languages; invariant, owned by fpg.vocab. */",
            f"export const QUERY_LANGUAGES = {_js([q.value for q in QueryLanguage])}",
            "",
        ]
    )
    return body


def _js(value: object) -> str:
    """JSON is a subset of JavaScript, so the values need no separate encoder."""
    return json.dumps(value, indent=2, ensure_ascii=False)


def main(argv: list[str]) -> None:
    check = "--check" in argv
    rendered = render_vocabulary_js()
    if check:
        current = VOCABULARY_JS.read_text(encoding="utf-8") if VOCABULARY_JS.is_file() else ""
        if current != rendered:
            raise SystemExit(f"{VOCABULARY_JS} is stale; regenerate it with `python -m autorl.fpg`")
        print(f"{VOCABULARY_JS} matches {PROFILE_PATH}")
        return
    VOCABULARY_JS.write_text(rendered, encoding="utf-8")
    print(f"wrote {VOCABULARY_JS} from {PROFILE_PATH} ({schema().profile.vocab_version})")


if __name__ == "__main__":
    main(sys.argv[1:])
