// GENERATED by `python -m autorl.fpg` from configs/fpg/microservices.toml.
// Do not edit: `scripts/check.sh` fails when this drifts from the profile.
// The profile is the vocabulary's single source of truth and `fpg` the
// structure's; this file only carries them across the language boundary
// into the tool that must reject an out-of-contract submission before it
// becomes a training example.

export const VOCAB_VERSION = "core-0.1.0+microservices-0.5.0"

/** Entity-reference format, byte-identical to the pattern the bound
 * pydantic models enforce. */
export const ENTITY_REF_PATTERN = "^(?:svc|link):[A-Za-z0-9][A-Za-z0-9._>-]*$"

/** Entity kinds a `subject` may name, coarsest first. */
export const ENTITY_TYPES = [
  {
    "prefix": "svc",
    "brief": "A service in the system under investigation, whether it serves requests or backs one that does (e.g. svc:checkout, svc:mongodb-orders)"
  },
  {
    "prefix": "link",
    "brief": "A directed service-to-service network path, for when the path itself is the faulty entity (e.g. link:frontend->profile)"
  }
]

/** Failure modes a node may assert. `other` is the escape hatch fpg
 * injects into every generated enum. */
export const NODE_PREDICATES = [
  {
    "value": "process_killed",
    "brief": "Service process terminated, not running"
  },
  {
    "value": "network_partitioned",
    "brief": "Process running but network completely severed"
  },
  {
    "value": "network_degraded",
    "brief": "Network path quality reduced (added delay, packet loss, corruption, bandwidth limit)"
  },
  {
    "value": "cpu_saturated",
    "brief": "CPU fully consumed, all request handling starved"
  },
  {
    "value": "memory_exhausted",
    "brief": "Memory under sustained pressure or OOM"
  },
  {
    "value": "gc_pressure",
    "brief": "GC storms causing repeated stop-the-world pauses"
  },
  {
    "value": "dns_broken",
    "brief": "DNS resolution fails or returns wrong addresses"
  },
  {
    "value": "clock_skewed",
    "brief": "System clock offset relative to the cluster"
  },
  {
    "value": "latency_degraded",
    "brief": "Specific request paths slow, local resources normal"
  },
  {
    "value": "error_rate_elevated",
    "brief": "Error rate higher than normal (timeouts, connection refused, exceptions)"
  },
  {
    "value": "data_corrupted",
    "brief": "Output data incorrect without explicit errors"
  },
  {
    "value": "flow_interrupted",
    "brief": "A specific request path through this service stopped; other endpoints healthy"
  },
  {
    "value": "resource_pool_exhausted",
    "brief": "Thread or connection pool fully occupied; all endpoints slow despite normal CPU/memory"
  },
  {
    "value": "traffic_amplification",
    "brief": "Abnormal request volume surge (retry storms, failover stampede)"
  },
  {
    "value": "other",
    "brief": "None of the above; say what the failure mode is in the evidence explanation. A recurring `other` is a missing vocabulary entry."
  }
]

/** Evidence query languages; invariant, owned by fpg.vocab. */
export const QUERY_LANGUAGES = [
  "sql",
  "promql",
  "logql",
  "http",
  "other"
]
